import = [
    "~/.config/alacritty/themes/themes/nightfly.toml"
]

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 1 
startup_mode = "Maximized"
decorations = "None"

[cursor]
style = {shape = "Underline", blinking = "On"}

[env]
TERM = "xterm-256color"
